# Generated by Django 3.2.18 on 2023-04-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230429_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='streets',
            new_name='name',
        ),
    ]
